name = "cfproxy"
type = "javascript"
compatibility_date = "2025-05-16"
main = "index.js"

# If you want Cloudflare to auto‑route your custom domain:
routes = ["*.letshost.dpdns.org/*"]
# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true


[vars]
BASE_URI = "https://reverse-proxy-server-o4li.onrender.com"
